# Generated by Django 3.2.9 on 2021-12-29 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_auto_20211228_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='network',
            name='profile',
        ),
        migrations.AddField(
            model_name='profile',
            name='net',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='perfil.network', verbose_name='network'),
        ),
    ]
