# Generated by Django 3.2.9 on 2021-12-29 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0003_auto_20211229_0127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='net',
        ),
        migrations.AddField(
            model_name='profile',
            name='net',
            field=models.ManyToManyField(blank=True, null=True, to='perfil.Network'),
        ),
    ]
