# Generated by Django 3.2.9 on 2021-12-29 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0004_auto_20211229_0145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='net',
        ),
        migrations.AddField(
            model_name='network',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='perfil.profile', verbose_name='network'),
        ),
    ]
