# Generated by Django 3.2.9 on 2021-12-29 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0005_auto_20211229_0151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='network',
            name='profile',
        ),
        migrations.AddField(
            model_name='network',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='network', to='perfil.profile'),
        ),
    ]
