# Generated by Django 3.2.11 on 2022-02-07 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0011_iconsocialnetwork'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iconsocialnetwork',
            name='name',
            field=models.CharField(blank=True, choices=[('YOUTUBE', 'youtube'), ('WHATSAPP', 'whatsapp'), ('FACEBOOK', 'facebook'), ('INSTAGRAM', 'instagram'), ('TWITTER', 'twitter'), ('PINTEREST', 'pinterest'), ('SNAPCHAT', 'snapchat'), ('TIKTOK', 'tiktok'), ('DISCORD', 'discord'), ('GITHUB', 'Github')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='network',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='icon_social_network', to='perfil.iconsocialnetwork'),
        ),
    ]
