# Generated by Django 4.1.2 on 2022-10-22 23:12

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0013_alter_network_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IconSocialNetwork',
        ),
        migrations.AlterField(
            model_name='network',
            name='name',
            field=models.CharField(blank=True, choices=[('youtube', 'youtube'), ('whatsapp', 'whatsapp'), ('facebook', 'facebook'), ('instagram', 'instagram'), ('twitter', 'twitter'), ('pinterest', 'pinterest'), ('snapchat', 'snapchat'), ('tiktok', 'tiktok'), ('discord', 'discord'), ('github', 'github')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=stdimage.models.StdImageField(blank=True, force_min_size=False, upload_to='profile', variations={'thumb': (500, 500, True)}, verbose_name='Image'),
        ),
    ]
