# Generated by Django 3.1 on 2022-11-09 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0014_delete_iconsocialnetwork_alter_network_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
