# Generated by Django 3.2.9 on 2022-01-16 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postfiles',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='post/file', verbose_name='files'),
        ),
    ]
