# Generated by Django 3.2.11 on 2022-01-16 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_postfiles_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='files1',
            field=models.FileField(blank=True, null=True, upload_to='post/file', verbose_name='files1'),
        ),
        migrations.AddField(
            model_name='post',
            name='files2',
            field=models.FileField(blank=True, null=True, upload_to='post/file', verbose_name='files2'),
        ),
        migrations.AddField(
            model_name='post',
            name='files3',
            field=models.FileField(blank=True, null=True, upload_to='post/file', verbose_name='files3'),
        ),
        migrations.DeleteModel(
            name='PostFiles',
        ),
    ]
