# Generated by Django 3.2.11 on 2022-02-02 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20220116_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialcomment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socialcomment', to='post.post'),
        ),
    ]
